name: Renovate

on:
  schedule:
    - cron: "/15 * * * *"
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@f9dfd286235d81ce4a68f95019018c2fd7df13a9 # v38.1.2
        with:
          configurationFile: .github/renovate-android.json
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          LOG_LEVEL: 'debug'
